<a href="https://colab.research.google.com/github/saulrubio75/lab-numpy/blob/master/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#1. Import the NUMPY package under the name np. 
import numpy as np 


In [56]:
#2. Print the NUMPY version and the configuration. 
np.__version__

'1.21.6'

In [57]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find? 
a = np.random.random((2, 3, 5)) 


In [7]:
#4. Print a. 
print(a)

[[[0.22061626 0.03956787 0.12436519 0.49482995 0.61523096]
  [0.2752473  0.95886793 0.8865649  0.52932595 0.95583747]
  [0.43054188 0.72482692 0.25826781 0.3425855  0.43286726]]

 [[0.15274832 0.28113295 0.39625428 0.86895    0.03224965]
  [0.10791113 0.23738388 0.70676912 0.21320371 0.61999786]
  [0.91363109 0.60221975 0.10354914 0.98968953 0.18382499]]]


In [59]:

#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b" 
b= np.ones((5, 2, 3)) 





 




[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
#6. Print b. 
print(b)

In [62]:
#7. Do a and b have the same size? How do you prove that in Python code? 
print(a.size == b.size)

True


In [63]:
#8. Are you able to add a and b? Why or why not?  
a + b # we can´t add a and b because it is not the same shape 



ValueError: ignored

In [67]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c". 

c = b.transpose() 
c = b.reshape(2, 3, 5)

print(c)






[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [69]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now? 

d = a + c  #This works 'cause we reshape b into the shape of a 
print(d)


[[[1.70545093 1.05375956 1.65640266 1.84122242 1.98486184]
  [1.16528782 1.80211606 1.53037329 1.61758331 1.80421208]
  [1.09143982 1.94143268 1.25727366 1.64219922 1.09262126]]

 [[1.88364845 1.0728972  1.09391193 1.77219534 1.18585808]
  [1.23653994 1.26110976 1.72429009 1.343431   1.4964224 ]
  [1.8501884  1.77996787 1.64215756 1.91902902 1.51070768]]]


In [72]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain. 

print(a)  #When we add this arrays we add the first number of the array a with the first number of  array c, and the second with the second




[[[0.70545093 0.05375956 0.65640266 0.84122242 0.98486184]
  [0.16528782 0.80211606 0.53037329 0.61758331 0.80421208]
  [0.09143982 0.94143268 0.25727366 0.64219922 0.09262126]]

 [[0.88364845 0.0728972  0.09391193 0.77219534 0.18585808]
  [0.23653994 0.26110976 0.72429009 0.343431   0.4964224 ]
  [0.8501884  0.77996787 0.64215756 0.91902902 0.51070768]]]


In [73]:
print(d)

[[[1.70545093 1.05375956 1.65640266 1.84122242 1.98486184]
  [1.16528782 1.80211606 1.53037329 1.61758331 1.80421208]
  [1.09143982 1.94143268 1.25727366 1.64219922 1.09262126]]

 [[1.88364845 1.0728972  1.09391193 1.77219534 1.18585808]
  [1.23653994 1.26110976 1.72429009 1.343431   1.4964224 ]
  [1.8501884  1.77996787 1.64215756 1.91902902 1.51070768]]]


In [74]:
#12. Multiply a and c. Assign the result to e. 
e = a * c 

In [78]:
#13. Does e equal to a? Why or why not? 
print(e) 


print(a) #Yes 'cause every number multiple by 1 it's the same number

[[[0.70545093 0.05375956 0.65640266 0.84122242 0.98486184]
  [0.16528782 0.80211606 0.53037329 0.61758331 0.80421208]
  [0.09143982 0.94143268 0.25727366 0.64219922 0.09262126]]

 [[0.88364845 0.0728972  0.09391193 0.77219534 0.18585808]
  [0.23653994 0.26110976 0.72429009 0.343431   0.4964224 ]
  [0.8501884  0.77996787 0.64215756 0.91902902 0.51070768]]]
[[[0.70545093 0.05375956 0.65640266 0.84122242 0.98486184]
  [0.16528782 0.80211606 0.53037329 0.61758331 0.80421208]
  [0.09143982 0.94143268 0.25727366 0.64219922 0.09262126]]

 [[0.88364845 0.0728972  0.09391193 0.77219534 0.18585808]
  [0.23653994 0.26110976 0.72429009 0.343431   0.4964224 ]
  [0.8501884  0.77996787 0.64215756 0.91902902 0.51070768]]]


In [81]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"  
d_max = d.max()
d_min = d.min() 
d_mean = d.mean() 


print(d_max) 
print(d_min) 
print(d_mean)


1.9848618384826209
1.0537595629946974
1.531953043922407


In [ ]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`. 

f = np.empty


In [86]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question. 
""" 
f= np.where(d==d_min, 0, np.where(d == d_max, 100, 
  np.where(d == d_mean, 50,
  np.where((d_min < d) & (d<d_mean), 25, 
  np.where((d_mean < d) & (d<d_max), 75, 1000)))))



In [87]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
""" 
print(f)
print(d)

[[[ 75   0  75  75 100]
  [ 25  75  25  75  75]
  [ 25  75  25  75  25]]

 [[ 75  25  25  75  25]
  [ 25  25  75  25  25]
  [ 75  75  75  75  25]]]
[[[1.70545093 1.05375956 1.65640266 1.84122242 1.98486184]
  [1.16528782 1.80211606 1.53037329 1.61758331 1.80421208]
  [1.09143982 1.94143268 1.25727366 1.64219922 1.09262126]]

 [[1.88364845 1.0728972  1.09391193 1.77219534 1.18585808]
  [1.23653994 1.26110976 1.72429009 1.343431   1.4964224 ]
  [1.8501884  1.77996787 1.64215756 1.91902902 1.51070768]]]


In [88]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
""" 

np.where(d == d_min,"A", 
np.where(d == d_max,"E", 
np.where(d == d_mean,"C", 
np.where((d > d_min) & (d < d_mean),"B",
np.where((d > d_mean) & (d < d_max),"D", 1000)))))

array([[['D', 'A', 'D', 'D', 'E'],
        ['B', 'D', 'B', 'D', 'D'],
        ['B', 'D', 'B', 'D', 'B']],

       [['D', 'B', 'B', 'D', 'B'],
        ['B', 'B', 'D', 'B', 'B'],
        ['D', 'D', 'D', 'D', 'B']]], dtype='<U21')